services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: game_store
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - game_store_data:/var/lib/postgresql/data
volumes:
  game_store_data: